export const DAMAGE = [
  "Sprednji levi zaromet/meglenka/smerokaz",
  "Sprednji levi blatnik",
  "Sprednje levo platisce/pnevmatika",
  "Sprednje levo ogledalo",
  "Leva vrata/kabina/streha",
  "Stranski levi spojler",
  "Medosni levi spojler",
  "Zadnji levi blatnik",
  "Zadnje levo platisce",
  "Zadnji levi zaromet/meglenka/smerokaz",
  "Sprednji odbijac",
  "Pokrov motorja",
  "Vetrobransko steklo",
  "Streha",
  "Zadnji del kabine",
  "Sprednji desni zaromet/meglenka/smerokaz",
  "Sprednji desni blatnik",
  "Sprednje desno platisce/pnevmatika",
  "Sprednje desno ogledalo",
  "Desna vrata/kabina/streha",
  "Stranski desni spojler",
  "Medosni desni spojler",
  "Zadnji desni blatnik",
  "Zadnje desno platisce",
  "Zadnji desni zaromet/meglenka/smerokaz"
];
